<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSixVPcH\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSixVPcH/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSixVPcH.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSixVPcH\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSixVPcH\App_KernelProdContainer([
    'container.build_hash' => 'SixVPcH',
    'container.build_id' => 'e82838c5',
    'container.build_time' => 1688070830,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSixVPcH');
