<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'all_movies' => [[], ['_controller' => 'App\\Controller\\MoviesController::allMovies'], [], [['text', '/api/v1/movies']], [], [], []],
    'get_one_movie' => [['id'], ['_controller' => 'App\\Controller\\MoviesController::getOneMovie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/movies']], [], [], []],
    'create_one_movie' => [[], ['_controller' => 'App\\Controller\\MoviesController::createOneMovie'], [], [['text', '/api/v1/movies']], [], [], []],
    'delete_one_movie' => [['id'], ['_controller' => 'App\\Controller\\MoviesController::deleteOneMovie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/movies']], [], [], []],
    'update_one_movie' => [['id'], ['_controller' => 'App\\Controller\\MoviesController::updateOneMovie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/movies']], [], [], []],
];
